[package]
name = "rosewood"
version = "0.1.0"
description = "A file-based RTree for geospatial data"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rosewood"
repository = "https://github.com/DougLau/loam/rosewood"
readme = "README.md"
keywords = ["geo", "spatial"]
edition = "2018"

[dependencies]
loam = { version = "0.1", path = "../loam" }
pointy = { version = "0.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
fastrand = "1.5"
